# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Alan Du
# tagline:          'A Jekyll theme'
description:      'College student interested in software, machine learning, and financial markets'
url:              https://ydu20.github.io
# baseurl:          /

# author:
#   name:           'Mark Otto'
#   url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/ydu20/ydu20.github.io

plugins:
  - jekyll-paginate
  - jekyll-gist
  - redcarpet